service:
  name: mailtumble-landing

custom:
  stage: ${opt:stage, self:provider.stage}

  region: ${opt:region, env:AWS_REGION, self:provider.region}

  client:
    bucketName: ${self:service.name}-${self:custom.stage}-dist
    distributionFolder: build
    indexDocument: index.html
    errorDocument: index.html

plugins:
  - serverless-finch

provider:
  name: aws

  runtime: nodejs12.x
